### ISSUE TITLE
complete all "todo: (sobuj)" in the code

### ISSUE THREAD

**Issue by murad073** [murad073/SmartAccount#10]
I have complete maximum todos. Some condition need your knowledge. i marked those todos as todo: (sobuj). Please remove the todos with necessery change in code (if needed).

**Comment by jakaria42** [comment]
I searched with "todo: (sobuj)", but did not find anything like this in the entire solution today. Did you remove them?

**Comment by murad073** [comment]
I gave full push.  
your task - 
1. fetch from murad073
2. fetch from origin if any
3. merge all branched
4. run the code successfully
5. commit every change
6. dont forget to push to origin (bkz i always observe the graph for branch traking - if u dont push, i get wrong information from the network graph)

**Comment by murad073** [comment]
if you finish all TODOs, please make the issue closed

**Comment by murad073** [comment]
please look at the issue and close the thread. 
// TODO: (sobuj) JV started unchecked does not work with JC Started checkbox disabled

**Comment by jakaria42** [comment]
I saw this, but don't understand what the the exact problem is.

Can you you describe what kind of problem we had there?
