### ISSUE TITLE
Narration in Journal Voucher

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#16]
I found this issue while making the voucher details view window.

We give multiple narrations (one for each entry) for JV. But when someone creates a JV on paper, s/he gives only one narration. We also need to show a narration while showing a JV. But we actually have several narrations.

Should we allow the user to post only one narration while creating a JV?

**Comment by murad073** [comment]
leave this enhancement now. keep as it is. we have lot other things to do..

**Comment by jakaria42** [comment]
After each temporary voucher, we will not remove the narration. We will take narration from the last entry and use for all the entries.

**Comment by jakaria42** [comment]
This is done. We now take only the final narration.
