### ISSUE TITLE
Reload button doesn't work correctly in Project setup tab

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#30]
In the Project Setup tab, if you click the the Reload button, then there are some problems:

After reloading, if there is only one project, then selecting the project from the first list-box doesn't call the SelectedProject property's set method. So nothing happens afterwards, that is, no list-box will be updated.

**Comment by jakaria42** [comment]
If there are multiple projects, then there is a bug, too. 

Say, you select Project1, it's heads are being shown in the middle list-box, and the right list-box shows all the remaining heads. Now, click the reload button, the middle and right list-box will be cleared. Click in the item Project1 in the first list-box. The other two lists will not be updated.

You need to select another project and then come back to Project1 to see the second and third lists correctly.

**Comment by murad073** [comment]
solved, commited, pushed.. :)
