### ISSUE TITLE
Post button is enabled wrongly for JV

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#33]
To duplicate: Start creating a JV. Make an entry in the temp grid, uncheck 'Start same JV'. There will be a message that the debit and credit balance is not zero. But the Post button will be enabled.

We should disable the post button in this case.

**Comment by murad073** [comment]
if you think the button works fine, just close the issue or solve as you want

**Comment by jakaria42** [comment]
I have solved this problem.
