### ISSUE TITLE
Contra voucher cannot be posted

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#35]
Right now, we cannot create and post a contra voucher. May be problem is in getting the head names for this to show in the temp  grid view.

**Comment by jakaria42** [comment]
I have pushed a fix for this.

**Comment by jakaria42** [comment]
The contra voucher serial number is still a problem. This is because contra voucher has no ProjectHead.

**Comment by jakaria42** [comment]
I have pushed a fix to this. But need confirmation about the DB structure.

**Comment by murad073** [comment]
Contra voucher will get Cash book and Bank book. as in code first approach, cash book and bank book is created first time the database created.

**Comment by murad073** [comment]
solved
