### ISSUE TITLE
CodeFirst Database

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#36]
Why isn't there any ProjectHeadID field in the Record table?

We don't have any ProjectHead for Cash/Bank book. That's why we have problems to entry contra voucher. We cannot get contra voucher serial number by calling GetNewVoucherNo.

**Comment by jakaria42** [comment]
I have pushed a fix for contra vouchers in MassVoucherManager::Set and MassVoucherManager::GetNewVoucherNo functions. Verify that these are correct for the current DB structure.

**Comment by murad073** [comment]
when database first create there must be cash book and bank book. 

We removed record.ProjectHeadId, we can find it from record.ProjectHead.ID
