### ISSUE TITLE
Download all changes

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#4]
I still cannot download all changes from murad073/SmartAccount.
I can see two repos here: 1. murad073/SmartAccount and 2. jakaria42/SmartAccount.
I have committed and pushed one change to jakaria42/SmartAccount, and I can see that there are some other changes in murad073/SmartAccount. But I cannot download them!
I tried fetch from origin and then local merge (not sure what the expression should be for local merge).

**Comment by murad073** [comment]
1.at the top right of the github screen, a "fork icon with number button" is showing after "watch icon with number button". click the "fork icon with number button".
2. click the 3rd tab, called "Fork Queue"
3. If you get some item with checkbox just check them, and from the combobox of Action, choose apply.
4. One conformation button will appear to confirm you. after clicking that button, the change will integrate with your repository branch.

Now from your local machine you can take my changes..

If you don't understand my instruction ...whenever you come online, just call me. I will tell you what to do.

**Comment by murad073** [comment]
http://www.perforce.com/downloads/complete_list

download and install the merge tool. In case of conflict, edit your conflict with this tool..

**Comment by jakaria42** [comment]
I followed your instructions on jakaria42/SmartAccount.
After I checked the ckeck boxes and changed the combo item to 'Apply', it showed me this message:

Clicking 'Update Branch' will update your current integration branch to include all of the 'applied' commits.
Any 'failed' commits will be left in your Fork Queue.
If you click 'Abort' nothing will change on your branch.

I clicked 'Update Branch', but the the items were still there. It seems that it didn't update my repo.

By the way, what are the procedures to bring these changes to my local pc? I opened SmartAccount with Git GUI, went to Remote | Fetch from | origin. Then I went to Merge | Local merge. Then what to do? What should I put in Revision expression edit box?

**Comment by jakaria42** [comment]
Now I'm sure that changing the combo item to 'Apply' didn't update my repo. Because it was shown in red color and there were failed tags after the check box items. 

FYI, I can see two changes my fork queue: your fix of messaging and my commit altering config files.
