### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#48]
Issue 1:
See public IList<Record> GetLedgerBook():
IList<Record> records = _recordRepository.Get() returns records for the selected project. But it returns 0 (zero) debit/credit for all the records which have LedgerType == LedgerBook.
This is why we see 0 amount in the ledger view / voucher view tab.

Issue 2:
In public IList<LedgerItem> LedgerDataGrid, how can we get the cheque no field from BankRecord table for a particular record?

Also similar to this: I need all the fields of the BankRecord table for a particular record in public IList<VoucherItem> VoucherDataGrid.

**Comment by jakaria42** [comment]
For issue 2: In the BankRecord table in the database, the field Record_ID is null. That is, there is a foreign key problem. I think, that's why the lambda expression is not working.

**Comment by murad073** [comment]
issue 1 is solved. I am now on issue 2.
