### ISSUE TITLE
Download changes

### ISSUE THREAD

**Issue by jakaria42** [murad073/SmartAccount#6]
I don't see any 'Fork Queue' tab in the 'Networks' tab.

How am supposed to take your changes to my repo 'jakaria42/SmartAccount'?

**Comment by murad073** [comment]
I am not getting the tab in my account too. I dont understand what is happening. You choose my branch directly to  get my changes.

steps - 
1. In your local git gui, add a remote named murad073 (location is : https://murad073@github.com/murad073/SmartAccount.git)
1. use facth from murad073
2. if you get some changes from me, try merge.

I think this will work...

I  still didnt get a good way to resolve conflict..., in case of conflict i dont know what to do..

**Comment by jakaria42** [comment]
I tried it, at first time, it showed me this message:
From https://github.com/murad073/SmartAccount
- [new branch]      master     -> Murad/master
  But actually it didn't fetch any new change.
