### ISSUE TITLE
Voucher View problem

### ISSUE THREAD

**Issue by murad073** [murad073/SmartAccount#61]
steps - 
1. Insert a Contra Voucher against a project
2. Insert a Credit Voucher against same project

in voucher view page, for the project if we view all voucher types, we will see - 
1. two entries for contra voucher (both cashbook and bank book entries)
but, 2. only one entry for Credit Voucher (no cashbook or bankbook entry shown)

-------do you think this is okay ? ...

**Comment by jakaria42** [comment]
I think that is fine. There is probably no better way to show the contra vouchers.
